// employee.model.ts
export interface Employee {
    id?: number;  // auto-generated by DB
    firstName: string;
    lastName: string;
    title: string;
    department: string;
    manager: string;
    joinDate: string;
    email: string;
    phone: string;
    about: string;
    skills: string[];
    experience: {
      title: string;
      company: string;
      period: string;
      description: string;
    }[];
  }
  